transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_21
vlib riviera/processing_system7_vip_v1_0_23
vlib riviera/xil_defaultlib
vlib riviera/xlconstant_v1_1_10
vlib riviera/proc_sys_reset_v5_0_17
vlib riviera/smartconnect_v1_0
vlib riviera/axi_register_slice_v2_1_35
vlib riviera/xpm_cdc_gen_v1_0_5
vlib riviera/axi_datamover_v5_1_37
vlib riviera/axi_sg_v4_1_21
vlib riviera/axi_dma_v7_1_36
vlib riviera/axis_infrastructure_v1_1_1
vlib riviera/axis_data_fifo_v2_0_17
vlib riviera/generic_baseblocks_v2_1_2
vlib riviera/fifo_generator_v13_2_13
vlib riviera/axi_data_fifo_v2_1_35
vlib riviera/axi_protocol_converter_v2_1_36
vlib riviera/axi_clock_converter_v2_1_34
vlib riviera/blk_mem_gen_v8_4_11
vlib riviera/axi_dwidth_converter_v2_1_36

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_21 riviera/axi_vip_v1_1_21
vmap processing_system7_vip_v1_0_23 riviera/processing_system7_vip_v1_0_23
vmap xil_defaultlib riviera/xil_defaultlib
vmap xlconstant_v1_1_10 riviera/xlconstant_v1_1_10
vmap proc_sys_reset_v5_0_17 riviera/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_register_slice_v2_1_35 riviera/axi_register_slice_v2_1_35
vmap xpm_cdc_gen_v1_0_5 riviera/xpm_cdc_gen_v1_0_5
vmap axi_datamover_v5_1_37 riviera/axi_datamover_v5_1_37
vmap axi_sg_v4_1_21 riviera/axi_sg_v4_1_21
vmap axi_dma_v7_1_36 riviera/axi_dma_v7_1_36
vmap axis_infrastructure_v1_1_1 riviera/axis_infrastructure_v1_1_1
vmap axis_data_fifo_v2_0_17 riviera/axis_data_fifo_v2_0_17
vmap generic_baseblocks_v2_1_2 riviera/generic_baseblocks_v2_1_2
vmap fifo_generator_v13_2_13 riviera/fifo_generator_v13_2_13
vmap axi_data_fifo_v2_1_35 riviera/axi_data_fifo_v2_1_35
vmap axi_protocol_converter_v2_1_36 riviera/axi_protocol_converter_v2_1_36
vmap axi_clock_converter_v2_1_34 riviera/axi_clock_converter_v2_1_34
vmap blk_mem_gen_v8_4_11 riviera/blk_mem_gen_v8_4_11
vmap axi_dwidth_converter_v2_1_36 riviera/axi_dwidth_converter_v2_1_36

vlog -work xilinx_vip  -incr "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"/tools/Xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_21  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_23  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
"../../../bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/sim/ila_pixclk.v" \
"../../../bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/sim/ila_refclk.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/DVI_Constants.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/ChannelBond.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/SyncAsync.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/GlitchFilter.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/TWI_SlaveCtl.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/EEPROM_8b.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/InputSERDES.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/PhaseAlign.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/ResyncToBUFG.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/SyncAsyncReset.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/SyncBase.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/TMDS_Clocking.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/TMDS_Decoder.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f99d/src/dvi2rgb.vhd" \
"../../../bd/design_1/ip/design_1_dvi2rgb_0_0/sim/design_1_dvi2rgb_0_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
"../../../bd/design_1/ip/design_1_tristate_0_0/sim/design_1_tristate_0_0.v" \
"../../../bd/design_1/ip/design_1_tristate_1_0/sim/design_1_tristate_1_0.v" \
"../../../bd/design_1/ipshared/2875/hdl/fir_interface_slave_lite_v1_0_S00_AXI.v" \
"../../../bd/design_1/ipshared/2875/hdl/fir_interface.v" \
"../../../bd/design_1/ip/design_1_fir_interface_0_1/sim/design_1_fir_interface_0_1.v" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \

vlog -work xlconstant_v1_1_10  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \

vcom -work proc_sys_reset_v5_0_17 -93  -incr \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arinsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rinsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awinsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_winsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_binsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_aroutsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_routsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_awoutsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_woutsw_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_boutsw_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_arni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_rni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_awni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_wni_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_bni_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_srn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_swn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_sbn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_48ac_m00arn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_48ac_m00rn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_48ac_m00awn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_48ac_m00wn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_48ac_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_48ac_m00e_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_48ac_m01s2a_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_48ac_m01arn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_48ac_m01rn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_48ac_m01awn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_48ac_m01wn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_48ac_m01bn_0.sv" \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_48ac_m01e_0.sv" \

vlog -work axi_register_slice_v2_1_35  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.sv" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_fir_wrapper_0_0/sim/design_1_fir_wrapper_0_0.v" \

vlog -work xpm_cdc_gen_v1_0_5  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/5f71/hdl/xpm_cdc_gen_v1_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_0_0/sim/design_1_xpm_cdc_gen_0_0.v" \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_1_0/sim/design_1_xpm_cdc_gen_1_0.v" \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_2_0/sim/design_1_xpm_cdc_gen_2_0.v" \
"../../../bd/design_1/ip/design_1_xpm_cdc_gen_3_0/sim/design_1_xpm_cdc_gen_3_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/d57c/src/ClockGen.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/d57c/src/OutputSERDES.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/d57c/src/TMDS_Encoder.vhd" \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/d57c/src/rgb2dvi.vhd" \
"../../../bd/design_1/ip/design_1_rgb2dvi_1_0/sim/design_1_rgb2dvi_1_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_ila_0_0/sim/design_1_ila_0_0.v" \

vcom -work axi_datamover_v5_1_37 -93  -incr \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_21 -93  -incr \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_36 -93  -incr \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/cb19/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_dma_0_0/sim/design_1_axi_dma_0_0.vhd" \

vlog -work axis_infrastructure_v1_1_1  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_17  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/e1e3/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axis_data_fifo_0_0/sim/design_1_axis_data_fifo_0_0.v" \
"../../../bd/design_1/ip/design_1_data_framer_w_0_0/sim/design_1_data_framer_w_0_0.v" \

vlog -work generic_baseblocks_v2_1_2  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_13  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/dc46/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_13 -93  -incr \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/dc46/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_13  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/dc46/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_35  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/4846/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_36  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_0/sim/design_1_axi_mem_intercon_imp_auto_pc_0.v" \

vlog -work axi_clock_converter_v2_1_34  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/9a28/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work blk_mem_gen_v8_4_11  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/a32c/simulation/blk_mem_gen_v8_4.v" \

vlog -work axi_dwidth_converter_v2_1_36  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../../lab3.gen/sources_1/bd/design_1/ipshared/db4c/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/6cfa/hdl" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a9be" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_refclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ip/design_1_dvi2rgb_0_0/src/ila_pixclk/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/5431/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/4e08/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/537f/hdl/verilog" "+incdir+../../../../lab3.gen/sources_1/bd/design_1/ipshared/d41f/hdl/verilog" "+incdir+/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_21 -l processing_system7_vip_v1_0_23 -l xil_defaultlib -l xlconstant_v1_1_10 -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_register_slice_v2_1_35 -l xpm_cdc_gen_v1_0_5 -l axi_datamover_v5_1_37 -l axi_sg_v4_1_21 -l axi_dma_v7_1_36 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_17 -l generic_baseblocks_v2_1_2 -l fifo_generator_v13_2_13 -l axi_data_fifo_v2_1_35 -l axi_protocol_converter_v2_1_36 -l axi_clock_converter_v2_1_34 -l blk_mem_gen_v8_4_11 -l axi_dwidth_converter_v2_1_36 \
"../../../bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_0/sim/design_1_axi_mem_intercon_imp_auto_us_0.v" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

